spring:
  application:
    name: portfolio
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/portfolio?retryWrites=true&w=majority}
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:your-s3-bucket-name}
    region: ${AWS_REGION:}
    presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:3600} # Default 1 hour in seconds
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: 8080

logging:
  level:
    com.berkay.portfolio: DEBUG
    org.springframework.data.mongodb: DEBUG

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
